# Generated by Django 4.2.6 on 2023-10-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0002_remove_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderdetails',
            name='financing_details',
            field=models.TextField(default='To be filled'),
        ),
    ]
