# Generated by Django 4.2.6 on 2023-10-22 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0004_alter_tenderdetails_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderdetails',
            name='financing',
        ),
        migrations.AlterField(
            model_name='tenderdetails',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.employee'),
        ),
    ]
